"""ApiKey Migration

Revision ID: 30ee94d70948
Revises: 96bab5c5f019
Create Date: 2018-04-25 11:55:56.484085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ee94d70948'
down_revision = '96bab5c5f019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikeys_api_key'), 'apikeys', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikeys_api_key'), table_name='apikeys')
    op.drop_table('apikeys')
    # ### end Alembic commands ###
