"""public_uid Migration

Revision ID: 8337f4128fa9
Revises: 30ee94d70948
Create Date: 2018-04-27 14:17:51.723017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8337f4128fa9'
down_revision = '30ee94d70948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_uid', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['public_uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'public_uid')
    # ### end Alembic commands ###
